bracketSpacing: true
printWidth: 120
proseWrap: "always"
singleQuote: false
tabWidth: 2
trailingComma: "all"
useTabs: false

# Support solidity options
overrides:
  - files:
      - "*.sol"
    options:
      printWidth: 120
      tabWidth: 4
      singleQuote: false
      explicitTypes: "always"
